### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by kainers1** [skainz92/wienernetze-smartmeter-php#10]
Wiener Netze dürften was umgebaut haben, Login funktioniert nicht mehr.
Habe diesen Issue dazu gefunden: https://github.com/platysma/vienna-smartmeter/issues/178

**Comment by realbadfox** [comment]
ja die dürften den Login auf zweistufig umgebaut haben, also zuerst email ==> klick ==> dann passwort ==> klick

**Comment by skainz92** [comment]
Gut, hab mir das mal angeschaut. 
Die verwenden jetzt alpine-js, und wie ihr schon sagt ist das login jetzt zweistufig, also komplett anders als es vorher war.

Das login muss komplett neu gemacht werden.
Das wird ein wenig dauern...

Hab noch nicht nachgeschaut, aber ich könnte mir vorstellen dass auch alle anderen Requests nicht mehr gehen werden.

**Comment by ASimb** [comment]
Hallo,
ich habe eine fork eröffnet, wo ich das login-Problem saniert habe. Außerdem gab es ein Problem mit der Funktion getConsumptionByDay(), die in der alten Version nicht mehr funktioniert hat. Habe ich auch saniert.

**Comment by ASimb** [comment]
Wichtiger Hinweis! Seit heute verlangt Wiener Netze die einmalige Akzeptanz der geänderten Nutzungsbedingungen beim erstmaligen Login. Bevor diese nicht bestätigt wurden, funktioniert der Login nicht. Daher scheint es so, als ob der Login via PHP-Library wieder nicht läuft. Lösung: einmalig direkt bei Wiener Netze einloggen und neue Nutzungsbedingungen akzeptieren, danach läuft alles wieder wie gehabt.

**Comment by realbadfox** [comment]
Funktioniert leider nicht bei mir :-( 
Habe bereits die Nutzungsbedingungen angenommen und die neue smartmeter-vienna.class.php eingefügt.
Aber bekomme beim Login.php leider "WN login error."

**Comment by ASimb** [comment]
Bei mir funktioniert es tadellos. Auf welcher Plattform betreibst Du es?

**Comment by realbadfox** [comment]
Bei mir am online web Server



-------- Ursprüngliche Nachricht --------
Von: Andreas Simbürger ***@***.***>
Datum: 04.01.25 18:01 (GMT+01:00)
An: skainz92/wienernetze-smartmeter-php ***@***.***>
Cc: realbadfox ***@***.***>, Comment ***@***.***>
Betreff: Re: [skainz92/wienernetze-smartmeter-php] Login error (Issue #10)


Bei mir funktioniert es tadellos. Auf welcher Plattform betreibst Du es?

**Comment by ASimb** [comment]
Hat die Ursprungsversion bis Dezember funktioniert bzw. hattest Du die in Betrieb, oder ist das eine Neuinstallation?

**Comment by realbadfox** [comment]
Ja bis die wiener Netze umgestellt haben hatte ich die alte Version dort in Verwendung


-------- Ursprüngliche Nachricht --------
Von: Andreas Simbürger ***@***.***>
Datum: 04.01.25 18:17 (GMT+01:00)
An: skainz92/wienernetze-smartmeter-php ***@***.***>
Cc: realbadfox ***@***.***>, Comment ***@***.***>
Betreff: Re: [skainz92/wienernetze-smartmeter-php] Login error (Issue #10)


Hat die Ursprungsversion bis Dezember funktioniert bzw. hattest Du die in Betrieb, oder ist das eine Neuinstallation?

**Comment by ASimb** [comment]
Hast Du sicher meine fork runtergeladen und nicht das Original? Curl ist installiert?

**Comment by realbadfox** [comment]
Hui curl ka. Muss ich sehen wie das geht. Ist ja ein gemieteter server für eine homepage


-------- Ursprüngliche Nachricht --------
Von: Andreas Simbürger ***@***.***>
Datum: 04.01.25 18:22 (GMT+01:00)
An: skainz92/wienernetze-smartmeter-php ***@***.***>
Cc: realbadfox ***@***.***>, Comment ***@***.***>
Betreff: Re: [skainz92/wienernetze-smartmeter-php] Login error (Issue #10)


Hast Du sicher meine fork runtergeladen und nicht das Original? Curl ist installiert?

**Comment by ASimb** [comment]
Hinweis: die funktionierende Version ist in dieser fork: https://github.com/ASimb/wienernetze-smartmeter-php

**Comment by realbadfox** [comment]
Ja die habe ich, aber funktioniert das auf einem webspace von world4you?


-------- Ursprüngliche Nachricht --------
Von: Andreas Simbürger ***@***.***>
Datum: 04.01.25 19:00 (GMT+01:00)
An: skainz92/wienernetze-smartmeter-php ***@***.***>
Cc: realbadfox ***@***.***>, Comment ***@***.***>
Betreff: Re: [skainz92/wienernetze-smartmeter-php] Login error (Issue #10)


Hinweis: die funktionierende Version ist in dieser fork: https://github.com/ASimb/wienernetze-smartmeter-php

**Comment by ASimb** [comment]
> Ja die habe ich, aber funktioniert das auf einem webspace von world4you?

Kann ich nicht sagen, aber wenn es vor Dezember funktioniert hat, dann sollte es jetzt auch gehen. Soviel hat sich im Login-Code nicht geändert. Auf meinem Raspi geht's einwandfrei.

**Comment by realbadfox** [comment]
Wie bekomme ich denn einen genaueren fehlercode raus? Damit ich das eingrenzen kann?

Von: Andreas Simbürger ***@***.***>
Gesendet: Samstag, 4. Jänner 2025 20:32
An: skainz92/wienernetze-smartmeter-php ***@***.***>
Cc: realbadfox ***@***.***>; Comment ***@***.***>
Betreff: Re: [skainz92/wienernetze-smartmeter-php] Login error (Issue #10)


Ja die habe ich, aber funktioniert das auf einem webspace von world4you?

Kann ich nicht sagen, aber wenn es vor Dezember funktioniert hat, dann sollte es jetzt auch gehen. Soviel hat sich im Login-Code nicht geändert. Auf meinem Raspi geht's einwandfrei.

**Comment by kainers1** [comment]
danke für den fork, klappt einwandfrei

Update: Eine Warnung habe ich schon: `PHP Warning:  Undefined property: stdClass::$error in /xxx/wienernetze-smartmeter-php/smartmeter-vienna.class.php on line 263`

**Comment by ASimb** [comment]
Ich habe herausgefunden, dass das WN-login MANCHMAL ein captcha-Rätsel lösen lässt, während man die Nutzerdaten eingeben soll. Ist das der Fall, scheitert das Login-script, weil das PHP als Bot identifiziert wird. Wann und unter welchen Umständen die Captcha-Prüfung gestartet wird, habe ich noch nicht erkannt. Wenn ich 2x ein falsches Passwort eingebe, startet Captcha und bleibt dann für einige Minuten, verschwindet aber wieder. Ich habe jetzt in die Login-Prozedur, 2x 1 Sekunde Wartezeit eingebaut, vielleicht hilft es.

**Comment by kainers1** [comment]
> Update: Eine Warnung habe ich schon: `PHP Warning: Undefined property: stdClass::$error in /xxx/wienernetze-smartmeter-php/smartmeter-vienna.class.php on line 263`

ein `isset()` müsste abhilfe schaffen:
```
			if(!isset($body->error)){
				$this->access_token = $body->access_token;
				return true;
			}
```
https://github.com/ASimb/wienernetze-smartmeter-php/blob/main/smartmeter-vienna.class.php#L265

Übrigens kommt bei jedem Login aus dem Ausland (meine VM steht in NL) eine Email; besser als ein Captcha.

> Hallo xxx,
>
> Wir haben festgestellt, dass sich jemand auf folgendem Gerät in Ihrem logwien Konto angemeldet hat:
> 
> Other Unknown - Gerät, null | Vereinigte Arabische Emirate | 05.01.2025, 03:31:07 GT
> 
> Waren Sie das?
> Wenn nicht, empfehlen wir Ihnen, das Passwort in ihrem logwien-Konto zu ändern.
> Falls Sie das selbst waren, müssen Sie nichts weiter unternehmen.
> 
> Liebe Grüße
> Ihr logwien

**Comment by realbadfox** [comment]
mh komisch bei mir bleibt der LoginError, keine Ahnung woran das liegt.

**Comment by realbadfox** [comment]
jetzt bekomme ich folgende Fehlermeldung: 
Warning: fopen(/var/smartmeter-vienna-wn.log): Failed to open stream: Operation not permitted in /home/.sites/78/site9846240/web/smartmeter/smartmeter-vienna.class.php on line 291

Fatal error: Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, false given in /home/.sites/78/site9846240/web/smartmeter/smartmeter-vienna.class.php:292
Stack trace:
#0 /home/.sites/78/site9846240/web/smartmeter/smartmeter-vienna.class.php(292): fwrite(false, 'REQUEST:\r\nhttps...')
#1 /home/.sites/78/site9846240/web/smartmeter/smartmeter-vienna.class.php(433): ViennaSmartmeter->wn('user/profile')
#2 /home/.sites/78/site9846240/web/smartmeter/login.php(5): ViennaSmartmeter->getProfile()
#3 {main}
  thrown in /home/.sites/78/site9846240/web/smartmeter/smartmeter-vienna.class.php on line 292

**Comment by ASimb** [comment]
> jetzt bekomme ich folgende Fehlermeldung: Warning: fopen(/var/smartmeter-vienna-wn.log): Failed to open stream: Operation not permitted in /home/.sites/78/site9846240/web/smartmeter/smartmeter-vienna.class.php on line 291
> 
> Fatal error: Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, false given in /home/.sites/78/site9846240/web/smartmeter/smartmeter-vienna.class.php:292 Stack trace: #0 /home/.sites/78/site9846240/web/smartmeter/smartmeter-vienna.class.php(292): fwrite(false, 'REQUEST:\r\nhttps...') #1 /home/.sites/78/site9846240/web/smartmeter/smartmeter-vienna.class.php(433): ViennaSmartmeter->wn('user/profile') #2 /home/.sites/78/site9846240/web/smartmeter/login.php(5): ViennaSmartmeter->getProfile() #3 {main} thrown in /home/.sites/78/site9846240/web/smartmeter/smartmeter-vienna.class.php on line 292

Sorry, mein Fehler: ich habe Zeilen eingefügt, die als debug die diversen Anfragen und Antworten zum/vom Server in log-Dateien schreiben. Der Pfad ist in der ersten Zeile des library `define("LogPath", "/var/");` hinterlegt. Ich habe es jetzt so korrigiert, dass nur im Falle von debug=true beim Initieren der Klasse die Dateien geschrieben werden. Also einfach mit `new ViennaSmartmeter([username], [password], false)` aufrufen, dann sollte das kein Problem mehr sein

**Comment by ASimb** [comment]
@captcha-problem: ich habe gestern bis Mitternacht Forschungsarbeit betrieben. Der login-Prozess (ohne captcha) läuft folgendermaßen:
1) unter "https://log.wien/auth/realms/logwien/protocol/openid-connect/auth?..." wird die Authentifizierung angefordert
2) der Server antwortet mit der Eingabemaske für den Benutzernamen. Darin befindet sich ein link hinter `action=` der, ergänzt um ein post-field mit dem username an den Server zurückgeschickt wird
3) der Server antwortet mit der Eingabemaske für das Passwort. Darin befindet sich ein link hinter `action=` der, ergänzt um zwei post-fields mit dem username und dem password an den Server zurückgeschickt wird
4) Danach werden noch 2x Daten ausgetauscht, bevor man das access-token erhält, ist aber an dieser Stelle nicht so interessant

Im Falle von einem friendlycaptcha-check wird zusätzlich von https://log.wien/auth/resources/ptm5k/login/logwien/friendlyCaptcha/widget.module.min.js ein javascript geladen, das prüft, ob es sich um einen Aufruf über einen Browser handelt und ob Interaktion mit dem Eingabeformular besteht. Wenn ja, wird ein kryptografisches "Rätsel" gelöst und vom Script in die Antwort (vgl. oben 2. und 3.) ein zusätzliches post-field mit `<input name="frc-captcha-solution" class="frc-captcha-solution" type="hidden" value="[Lösung des Rätsels]">` eingefügt, das dann beim Abschicken des Passworts und/oder des Usernamen mit an den Server übermittelt wird und dort verifiziert werden kann. Das Rätsel wird irgendwie mit folgendem link `https://eu-api.friendlycaptcha.eu/api/v1/puzzle?sitekey=FCMV49TQVEN4VSOA` abgerufen und vom Script gelöst. Der entscheidende Punkt: das Script im Browser löst das Rätsel und man könnte es in PHP nachbauen. Dazu fehlen mir aber die Kenntnisse in Javascript, um das JS-Original ausreichend zu verstehen.

**Comment by realbadfox** [comment]
ah jetzt funktioniert es auch bei mir, danke jungs

**Comment by realbadfox** [comment]
KÖnnt ihr mir helfen, wenn ich die getConsumptionByDay 2 x hintereinander ausführen möchte (1xEinspeisung + 1xBezug), dann funktioniert die 2. Abfrage nicht. Was muss ich hier machen?

**Comment by ASimb** [comment]
Kannst Du dein PHP-script posten? Sonst wird das spekulativ.

**Comment by realbadfox** [comment]
`include "php-funktionen.php";
require_once("smartmeter-vienna.class.php");
$sm = new ViennaSmartmeter("xxxxx", "xxxxx", false);
if ($sm->login()) {
	$me = $sm->getProfile();
	
} else {
	echo "WN login error.";
}	

function alert($msg) {
    echo "<script type='text/javascript'>alert('$msg');</script>";
}

// Abfrage der PV Anlage
//$datum = $_POST["datum"];
$datum = "2025-01-09";


$zaehlpunktverbrauch = "1250169382/AT0010000000000000001000015123643";
$zaehlpunkteinspeisung = "1250169382/AT0010000000000000001000015249841";

// Zählerstand ----------------------------------------------------------
$defaultGeschaeftspartnerRegistration = $me->defaultGeschaeftspartnerRegistration->geschaeftspartner;
$verbrauchvalues = $sm->getConsumptionByDay("AT0010000000000000001000015123643", $defaultGeschaeftspartnerRegistration, $dateFrom);
$einspeisungvalues = $sm->getConsumptionByDay("AT0010000000000000001000015249841", $defaultGeschaeftspartnerRegistration, $dateFrom);	`

**Comment by ASimb** [comment]
OK, ich habe auch 2 Zählpunkte und da funktioniert es einwandfrei. Hattest Du den library in der Vergangenheit schon mit dieser Konfiguration im Einsatz? Bei deinem 2. Zähler handelt es sich um einenen Einspeisezähler, vielleicht ist das das Problem. Kannst Du mal das Ergebnis der 2. Abfrage ("print_r()") posten? Du kannst auch mal die Funktion "getConsumptionData()" ausprobiert, ob die etwas liefert.

**Comment by realbadfox** [comment]
ja genau so, und auch schon mit mehreren anderen abfragen danach! aber irgendwie nach der ersten abfrage wollen alle anderen nicht mehr.
Response ist:
Array ( )

**Comment by realbadfox** [comment]
Keine Idee woran es liegen könnte?
Ich komme nicht weiter

**Comment by ASimb** [comment]
Auf welcher Pattform läuft es denn?

**Comment by realbadfox** [comment]
Webserver apache



MfG Christoph Püler



-------- Ursprüngliche Nachricht --------
Von: Andreas Simbürger ***@***.***>
Datum: 17.01.25 08:58 (GMT+01:00)
An: skainz92/wienernetze-smartmeter-php ***@***.***>
Cc: realbadfox ***@***.***>, Comment ***@***.***>
Betreff: Re: [skainz92/wienernetze-smartmeter-php] Login error (Issue #10)


Auf welcher Pattform läuft es denn?

**Comment by ASimb** [comment]
Eventuell beim initialisieren debug aktivieren. Dazu musst Du aber vorher im library ganz oben das Verzeichnis angeben, wo die debug-Dateien hingeschrieben werden. Anhand der Dateien kann man eher sehen, woran es hakt.

**Comment by realbadfox** [comment]
Wie genau aktiviere ich das debugging?

Von: Andreas Simbürger ***@***.***>
Gesendet: Freitag, 17. Jänner 2025 09:30
An: skainz92/wienernetze-smartmeter-php ***@***.***>
Cc: realbadfox ***@***.***>; Comment ***@***.***>
Betreff: Re: [skainz92/wienernetze-smartmeter-php] Login error (Issue #10)


Eventuell beim initialisieren debug aktivieren. Dazu musst Du aber vorher im library ganz oben das Verzeichnis angeben, wo die debug-Dateien hingeschrieben werden. Anhand der Dateien kann man eher sehen, woran es hakt.

**Comment by realbadfox** [comment]
Hello, so erstes Problem gelöst mal, getconsumptionperday funktioniert!
Es liegt an der Rolle! Diese muss mitgeschickt werden, diese habt ihr fix mit V002 drinnen.
Das ist aber nicht immer so. Ich bin auch in einer Energiegemeinschaft, daher ist diese Rolle anscheinend wichtig.

Jetzt versuche ich noch die getMeasurements zum Laufen zu bringen, weiß aber nicht wie man dort die Rolle mitschicken muss.


Von: Andreas Simbürger ***@***.***>
Gesendet: Freitag, 17. Jänner 2025 09:30
An: skainz92/wienernetze-smartmeter-php ***@***.***>
Cc: realbadfox ***@***.***>; Comment ***@***.***>
Betreff: Re: [skainz92/wienernetze-smartmeter-php] Login error (Issue #10)


Eventuell beim initialisieren debug aktivieren. Dazu musst Du aber vorher im library ganz oben das Verzeichnis angeben, wo die debug-Dateien hingeschrieben werden. Anhand der Dateien kann man eher sehen, woran es hakt.

**Comment by ASimb** [comment]
Ok, danke, wieder etwas gelernt!

**Comment by realbadfox** [comment]
Aber hast von den 2 Methoden eine curl API Schnittstellen beschreibung?

Damit ich weiß wie das zu schicken ist?


-------- Ursprüngliche Nachricht --------
Von: Andreas Simbürger ***@***.***>
Datum: 20.01.25 17:22 (GMT+01:00)
An: skainz92/wienernetze-smartmeter-php ***@***.***>
Cc: realbadfox ***@***.***>, Comment ***@***.***>
Betreff: Re: [skainz92/wienernetze-smartmeter-php] Login error (Issue #10)


Ok, danke, wieder etwas gelernt!

**Comment by ASimb** [comment]
Leider nicht, alles trail and error.
Btw: Wenn du getConsumptionData() verwendest, kannst Du als 5. Parameter die Rolle angeben.
